# Generated by Django 5.2.1 on 2025-06-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
