# Generated by Django 5.2.1 on 2025-06-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
